services:
  cellularscanner:
    image: "cellularscanner_ai:${SCANNER_AI_VERSION:-latest}"
    container_name: cellular_scanner_ai
    ports:
      - 4444:4444
    volumes:
      - ${SCANNER_AI_LOW_POWER_SAMPLES:-./samples}:/app/SAMPLES_LOW_POWER
    environment:
      - SCANNER_AI_PORT=4444
      - SAVE_SAMPLES=NO
      - MEM_OPTIMIZATION=YES
      - MAX_THREADS=2
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - MALLOC_ARENA_MAX=2
      - TORCH_THREADS=4
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 1g
    ulimits:
      core: -1
    restart: always
    tty: true
    networks:
      - docker-network

networks:
  docker-network:
    external: true
